language: php
sudo: false

php:
  - 7.0
  - 7.1

addons:
  rethinkdb: "2.3"

cache:
  directories:
    - /home/travis/build/RoySegall/nuntius-bot/vendor

before_script:

  # Install MongoDB for PHP.
  # source: https://gist.github.com/gyndav/2351174.
  - wget http://pecl.php.net/get/mongo-1.2.10.tgz
  - tar -xzf mongo-1.2.10.tgz
  - sh -c "cd mongo-1.2.10 && phpize && ./configure && sudo make install"
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

  # Installing composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --dev

  # Set up stuff for the webhooks tests.
  - nohup php -S localhost:8888 > /dev/null 2>&1 &
  - export NUNTIUS_BASE_URL=http://localhost:8888

script:
  - cp settings/credentials.local.travis.yml settings/credentials.local.yml
  - cp settings/hooks.local.travis.yml settings/hooks.local.yml
  - php console.php nuntius:install
  - vendor/phpunit/phpunit/phpunit --bootstrap vendor/autoload.php tests/
