language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

addons:
  rethinkdb: "2.3"

cache:
  directories:
    - /home/travis/build/RoySegall/gizra_slack_bot/vendor

before_script:
  # Installing composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - rethinkdb > /dev/null &
  - php install.php
  - vendor/phpunit/phpunit/phpunit --bootstrap vendor/autoload.php tests/
