language: php
sudo: false

php:
  - 7.0
  - 7.1

addons:
  rethinkdb: "2.3"

services:
  - mongodb

env:
  db_driver:
    - rethinkdb
    - mongodb

cache:
  directories:
    - /home/travis/build/RoySegall/nuntius-bot/vendor

before_script:

  - echo $db_driver

  # Install MongoDB for PHP.
  # source: https://gist.github.com/gyndav/2351174.
  - wget http://pecl.php.net/get/mongodb-1.4.3.tgz
  - tar -xzf mongodb-1.4.3.tgz
  - sh -c "cd mongodb-1.4.3 && pecl install mongodb"
  - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

  # Installing composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --dev

  # Set up stuff for the webhooks tests.
  - nohup php -S localhost:8888 > /dev/null 2>&1 &
  - export NUNTIUS_BASE_URL=http://localhost:8888

script:
  - cp settings/credentials.local.travis.yml settings/credentials.local.yml
  - cp settings/hooks.local.travis.yml settings/hooks.local.yml
  - php console.php nuntius:install
  - vendor/phpunit/phpunit/phpunit --bootstrap vendor/autoload.php tests/
