services:

  rethinkdb:
     class: \Nuntius\NuntiusRethinkdb

  manager.entity:
    class: \Nuntius\EntityManager
    arguments: ['@rethinkdb']

  manager.task:
    class: \Nuntius\TasksManager
    arguments: ['@rethinkdb', '@manager.entity']

  manager.update:
    class: \Nuntius\UpdateManager
    arguments: ['@rethinkdb', '@manager.entity']
