services:

  config:
    class: \Nuntius\NuntiusConfig

  rethinkdb:
    class: \Nuntius\NuntiusRethinkdb
    arguments: ['@config']

  manager.entity:
    class: \Nuntius\EntityManager
    arguments: ['@rethinkdb']

  manager.task:
    class: \Nuntius\TasksManager
    arguments: ['@rethinkdb', '@manager.entity']

  manager.update:
    class: \Nuntius\UpdateManager
    arguments: ['@rethinkdb', '@manager.entity']

  dispatcher:
    class: \Nuntius\NuntiusDispatcher
    arguments: []
