rethinkdb:
  host:
  port:
  db:
  api_key:
  timeout:
events:
  presence_change: '\Nuntius\Plugin\PresenceChange'
  message: '\Nuntius\Plugin\Message'
entities:
  reminders: '\Nuntius\Entity\Reminders'
  context: '\Nuntius\Entity\Context'
  context_archive: '\Nuntius\Entity\RunningContext'
  running_context: '\Nuntius\Entity\RunningContext'
  system: '\Nuntius\Entity\System'
  logger: '\Nuntius\Entity\Logger'
tasks:
  reminders: '\Nuntius\Tasks\Reminders'
  help: '\Nuntius\Tasks\Help'
  introduction: '\Nuntius\Tasks\Introduction'
updates:
  1: '\Nuntius\Update\Update1'
commands:
  - '\Nuntius\Commands\UpdateCommand'
  - '\Nuntius\Commands\InstallCommand'
webhooks:
  github:
    opened: '\Nuntius\Webhooks\GitHub\Opened'
dispatcher:
  names: '\Nuntius\Examples\Names\NameEvent'
dispatchers:
  names:
    tom: '\Nuntius\Examples\Names\Tom::name'
    hal: '\Nuntius\Examples\Names\HAL9000::name'
access_token: ''
