rethinkdb:
  host:
  port:
  db:
  api_key:
  timeout:
events:
  presence_change: '\Nuntius\Plugin\PresenceChange'
  message: '\Nuntius\Plugin\Message'
entities:
  reminders: '\Nuntius\Entity\Reminders'
tasks:
  reminders: '\Nuntius\Tasks\Reminders'
  help: '\Nuntius\Tasks\Help'
access_token: ''
