rethinkdb:
  host:
  port:
  db:
  api_key:
  timeout:
events:
  presence_change: '\Nuntius\Plugin\PresenceChange'
  message: '\Nuntius\Plugin\Message'
entities:
  reminders: '\Nuntius\Entity\Reminders'
  context: '\Nuntius\Entity\Context'
  running_context: '\Nuntius\Entity\RunningContext'
  system: '\Nuntius\Entity\System'
tasks:
  reminders: '\Nuntius\Tasks\Reminders'
  help: '\Nuntius\Tasks\Help'
  introduction: '\Nuntius\Tasks\Introduction'
updates:
  '1': '\Nuntius\Update\Update1'
  '2': '\Nuntius\Update\Update1'
commands:
  - '\Nuntius\Commands\UpdateCommand'
access_token: ''
