rethinkdb:
  host: localhost
  port: 28015
  db: nuntius
  api_key:
  timeout: 30
access_token: 'dummy'
dispatchers:
  github_opened:
    notify_user: '\tests\overrides\NuntiusGitHubOpenedExampleOverride::act'
