services:

  config:
    class: \Nuntius\NuntiusConfig

  http:
    class: \GuzzleHttp\Client

  context:
    class: \Nuntius\ContextManager

  facebook_send_api:
    class: \FacebookMessengerSendApi\SendAPI

  db:
    class: \Nuntius\Db\DbDispatcher
    arguments: ['@config']

  dispatcher:
    class: \Nuntius\NuntiusDispatcher
    arguments: ['@config']

  rethinkdb:
    class: \Nuntius\NuntiusRethinkdb
    arguments: ['@config']

  manager.entity:
    class: \Nuntius\EntityManager
    arguments: ['@db', '@config']

  manager.task:
    class: \Nuntius\TasksManager
    arguments: ['@db', '@manager.entity', '@config']

  manager.update:
    class: \Nuntius\UpdateManager
    arguments: ['@db', '@manager.entity', '@config']

  manager.fb_postback:
    class: \Nuntius\FbPostBackManager
    arguments: ['@facebook_send_api', '@config']

  manager.cron:
    class: \Nuntius\CronManager
    arguments: ['@config']
